/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("com.android.library")
    kotlin("android")
}

android {
    namespace = "org.zingolabs.zingolib_android"
    compileSdk = 34

    defaultConfig {
        minSdk = 21
        testOptions.targetSdk = 34
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    sourceSets {
        getByName("androidTest").java.srcDirs("src/androidTest/kotlin")
    }

    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)
    // Native interop (optional for tests using JNA or UniFFI)
    // Note that the `aar` here is important, as otherwise it won't be able to find some .so files.
    implementation("net.java.dev.jna:jna:5.17.0@aar")

    // Android test dependencies
    androidTestImplementation(libs.junit)
    androidTestImplementation(libs.core)
    androidTestImplementation(libs.runner)
    androidTestImplementation(libs.rules)
    androidTestImplementation(libs.espresso.core)
}
